-- Imports
local colors = require('kyomi.colors')

-- Declare the main table
local Module = {
    -- Define polished colors
    polish_hl = {
        -- Treesitter highlights
        ['@punctuation.bracket'] = { fg = colors.base_30.white },
        ['@punctuation.delimiter'] = { fg = colors.base_30.white },
        ['@tag.delimiter'] = { fg = colors.base_30.white },
        ['@parameter'] = { fg = colors.base_30.white },
        ['@field'] = { fg = colors.base_30.purple },
        ['@property'] = { fg = colors.base_30.purple },
        ['@variable'] = { fg = colors.base_30.purple },
        ['@variable.builtin'] = { fg = colors.base_30.teal },
        ['@constant.builtin'] = { fg = colors.base_30.teal },
        ['@module'] = { fg = colors.base_30.teal },
        ['@function.builtin'] = { fg = colors.base_30.pink },
        ['@function'] = { fg = colors.base_30.pink },
        ['@constructor'] = { fg = colors.base_30.teal },
        ['@keyword'] = { fg = colors.base_30.blue },
        ['@keyword.return'] = { fg = colors.base_30.blue },
        ['@keyword.function'] = { fg = colors.base_30.blue },
        ['@keyword.operator'] = { fg = colors.base_30.blue },
        ['@operator'] = { fg = colors.base_30.white },
        ['@string'] = { fg = colors.base_30.yellow },
        ['@string.regex'] = { fg = colors.base_30.white },
        ['@string.escape'] = { fg = colors.base_30.white },
        ['@type'] = { fg = colors.base_30.teal },
        ['@type.builtin'] = { fg = colors.base_30.teal },
        ['@attribute'] = { fg = colors.base_30.white },
        ['@tag'] = { fg = colors.base_30.purple },
        ['@tag.attribute'] = { fg = colors.base_30.white },
        ['@namespace'] = { fg = colors.base_30.teal },
        ['@symbol'] = { fg = colors.base_30.white },
        ['@text.reference'] = { fg = colors.base_30.pink },
        ['@text.title'] = { fg = colors.base_30.purple },
        ['@text.underline'] = { fg = colors.base_30.blue },
        ['@text.uri'] = { fg = colors.base_30.blue },
        ['@text.literal'] = { fg = colors.base_30.yellow },
        ['@text.todo'] = { fg = colors.base_30.black, bg = colors.base_30.yellow },
        ['@comment'] = { fg = colors.base_16.base0F, italic = true },
        ['@punctuation.special'] = { fg = colors.base_30.yellow },
        ['@text.note'] = { fg = colors.base_30.pink },
        ['@text.warning'] = { fg = colors.base_30.white },
        ['@text.danger'] = { fg = colors.base_30.red },
        ['@text.debug'] = { fg = colors.base_30.blue },

        -- Language-specific highlights
        ['@punctuation.definition.delayed.unison'] = { fg = colors.base_30.purple },
        ['@storage.type.haskell'] = { fg = colors.base_30.white },
        ['@support.variable.magic.python'] = { fg = colors.base_30.purple },
        ['@punctuation.separator.period.python'] = { fg = colors.base_30.white },
        ['@variable.parameter.function.language.special.self.python'] = { fg = colors.base_30.teal },
        ['@storage.modifier.lifetime.rust'] = { fg = colors.base_30.white },
        ['@support.function.std.rust'] = { fg = colors.base_30.pink },
        ['@entity.name.lifetime.rust'] = { fg = colors.base_30.teal },
        ['@variable.language.rust'] = { fg = colors.base_30.purple },
        ['@constant.other.character-class.regexp'] = { fg = colors.base_30.purple },
        ['@keyword.operator.quantifier.regexp'] = { fg = colors.base_30.white },
        ['@punctuation.definition.string'] = { fg = colors.base_30.yellow },
        ['@variable.parameter.function'] = { fg = colors.base_30.white },
        ['@comment.markup.link'] = { fg = colors.base_16.base0F },
        ['@markup.changed.diff'] = { fg = colors.base_30.teal },
        ['@meta.diff.header.from-file'] = { fg = colors.base_30.pink },
        ['@markup.inserted.diff'] = { fg = colors.base_30.yellow },
        ['@markup.deleted.diff'] = { fg = colors.base_30.purple },
        ['@meta.function.c'] = { fg = colors.base_30.purple },
        ['@punctuation.section.block.begin.bracket.curly.cpp'] = { fg = colors.base_30.white },
        ['@punctuation.separator.key-value'] = { fg = colors.base_30.white },
        ['@keyword.operator.expression.import'] = { fg = colors.base_30.pink },
        ['@support.constant.math'] = { fg = colors.base_30.teal },
        ['@variable.other.constant'] = { fg = colors.base_30.teal },
        ['@storage.type.annotation.java'] = { fg = colors.base_30.teal },
        ['@source.java'] = { fg = colors.base_30.purple },
        ['@punctuation.section.block.begin.java'] = { fg = colors.base_30.white },
        ['@meta.method.java'] = { fg = colors.base_30.pink },
        ['@storage.modifier.import.java'] = { fg = colors.base_30.teal },
        ['@keyword.operator.instanceof.java'] = { fg = colors.base_30.blue },
        ['@meta.definition.variable.name.java'] = { fg = colors.base_30.purple },
        ['@keyword.operator.logical'] = { fg = colors.base_30.white },
        ['@support.constant.property-value.scss'] = { fg = colors.base_30.white },
        ['@keyword.operator.css'] = { fg = colors.base_30.white },
        ['@support.module.node'] = { fg = colors.base_30.teal },
        ['@entity.name.type.module'] = { fg = colors.base_30.teal },
        ['@variable.other.readwrite'] = { fg = colors.base_30.purple },
        ['@support.constant.json'] = { fg = colors.base_30.white },
        ['@keyword.operator.expression.instanceof'] = { fg = colors.base_30.blue },
        ['@support.type.object.console'] = { fg = colors.base_30.purple },
        ['@entity.name.function'] = { fg = colors.base_30.pink },
        ['@support.function.console'] = { fg = colors.base_30.pink },
        ['@keyword.operator.misc.rust'] = { fg = colors.base_30.white },
        ['@keyword.operator.sigil.rust'] = { fg = colors.base_30.blue },
        ['@keyword.operator.delete'] = { fg = colors.base_30.blue },
        ['@support.type.object.dom'] = { fg = colors.base_30.white },
        ['@support.variable.dom'] = { fg = colors.base_30.purple },
        ['@keyword.operator.arithmetic'] = { fg = colors.base_30.white },
        ['@keyword.operator.assignment.c'] = { fg = colors.base_30.blue },
        ['@punctuation.separator.delimiter'] = { fg = colors.base_30.white },
        ['@support.type.posix-reserved.c'] = { fg = colors.base_30.white },
        ['@keyword.operator.sizeof.c'] = { fg = colors.base_30.blue },
        ['@variable.parameter.function.language.python'] = { fg = colors.base_30.white },
        ['@support.type.python'] = { fg = colors.base_30.white },
        ['@keyword.operator.logical.python'] = { fg = colors.base_30.blue },
        ['@variable.parameter.function.python'] = { fg = colors.base_30.white },
        ['@punctuation.definition.arguments.begin.python'] = { fg = colors.base_30.white },
        ['@meta.function-call.generic.python'] = { fg = colors.base_30.pink },
        ['@constant.character.format.placeholder.other.python'] = { fg = colors.base_30.white },
        ['@keyword.operator'] = { fg = colors.base_30.white },
        ['@keyword.operator.assignment.compound'] = { fg = colors.base_30.blue },
        ['@keyword'] = { fg = colors.base_30.blue },
        ['@entity.name.namespace'] = { fg = colors.base_30.teal },
        ['@variable'] = { fg = colors.base_30.purple },
        ['@variable.c'] = { fg = colors.base_30.white },
        ['@variable.language'] = { fg = colors.base_30.teal },
        ['@token.variable.parameter.java'] = { fg = colors.base_30.white },
        ['@import.storage.java'] = { fg = colors.base_30.teal },
        ['@token.package.keyword'] = { fg = colors.base_30.blue },
        ['@token.package'] = { fg = colors.base_30.white },
        ['@entity.name.function'] = { fg = colors.base_30.pink },
        ['@entity.name.type.class'] = { fg = colors.base_30.teal },
        ['@entity.name.class'] = { fg = colors.base_30.teal },
        ['@variable.other.class.php'] = { fg = colors.base_30.purple },
        ['@entity.name.type'] = { fg = colors.base_30.teal },
        ['@keyword.control'] = { fg = colors.base_30.blue },
        ['@keyword.other.special-method'] = { fg = colors.base_30.pink },
        ['@storage'] = { fg = colors.base_30.blue },
        ['@token.storage'] = { fg = colors.base_30.blue },
        ['@token.storage.type.java'] = { fg = colors.base_30.teal },
        ['@support.function'] = { fg = colors.base_30.white },
        ['@support.type.property-name'] = { fg = colors.base_30.white },
        ['@meta.tag'] = { fg = colors.base_30.white },
        ['@string'] = { fg = colors.base_30.yellow },
        ['@entity.other.inherited-class'] = { fg = colors.base_30.teal },
        ['@constant.other.symbol'] = { fg = colors.base_30.white },
        ['@constant.numeric'] = { fg = colors.base_30.white },
        ['@constant'] = { fg = colors.base_30.white },
        ['@entity.name.tag'] = { fg = colors.base_30.purple },
        ['@entity.other.attribute-name'] = { fg = colors.base_30.white },
        ['@entity.other.attribute-name.id'] = { fg = colors.base_30.pink },
        ['@entity.other.attribute-name.class.css'] = { fg = colors.base_30.white },
        ['@meta.selector'] = { fg = colors.base_30.blue },
        ['@markup.heading'] = { fg = colors.base_30.purple },
        ['@markup.heading.punctuation.definition.heading'] = { fg = colors.base_30.pink },
        ['@keyword.other.unit'] = { fg = colors.base_30.purple },
        ['@markup.bold'] = { fg = colors.base_30.white },
        ['@punctuation.definition.bold'] = { fg = colors.base_30.teal },
        ['@markup.italic'] = { fg = colors.base_30.blue, italic = true },
        ['@punctuation.definition.list.begin.markdown'] = { fg = colors.base_30.purple },
        ['@markup.inline.raw.markdown'] = { fg = colors.base_30.yellow },
        ['@markup.underline.link.markdown'] = { fg = colors.base_30.blue },
        ['@string.other.link.title.markdown'] = { fg = colors.base_30.pink },
        ['@string.regexp'] = { fg = colors.base_30.white },
        ['@constant.character.escape'] = { fg = colors.base_30.white },
        ['@punctuation.section.embedded'] = { fg = colors.base_30.purple },
        ['@invalid.illegal'] = { fg = '#ffffff' },
        ['@source.json.meta.structure.dictionary.json.tring.quoted.json'] = { fg = colors.base_30.purple },
        ['@source.json.meta.structure.dictionary.json.value.json.string.quoted.json'] = { fg = colors.base_30.yellow },
        ['@source.json.meta.structure.dictionary.json.onstant.language.json'] = { fg = colors.base_30.white },
        ['@support.type.property-name.json'] = { fg = colors.base_30.purple },
        ['@text.html.laravel-blade.source.php.embedded.line.html.entity.name.tag.laravel-blade'] = { fg = colors.base_30.blue },
        ['@support.other.namespace.use.php'] = { fg = colors.base_30.teal },
        ['@keyword.operator.error-control.php'] = { fg = colors.base_30.blue },
        ['@keyword.operator.type.php'] = { fg = colors.base_30.blue },
        ['@punctuation.section.array.begin.php'] = { fg = colors.base_30.white },
        ['@storage.type.php'] = { fg = colors.base_30.teal },
        ['@meta.function-call.php'] = { fg = colors.base_30.pink },
        ['@punctuation.definition.parameters.begin.bracket.round.php'] = { fg = colors.base_30.white },
        ['@support.constant.core.php'] = { fg = colors.base_30.white },
        ['@entity.name.goto-label.php'] = { fg = colors.base_30.pink },
        ['@keyword.operator.logical.php'] = { fg = colors.base_30.white },
        ['@keyword.operator.regexp.php'] = { fg = colors.base_30.blue },
        ['@keyword.operator.comparison.php'] = { fg = colors.base_30.white },
        ['@meta.function.decorator.python'] = { fg = colors.base_30.pink },
        ['@support.token.decorator.python'] = { fg = colors.base_30.white },
        ['@function.parameter'] = { fg = colors.base_30.white },
        ['@function.brace'] = { fg = colors.base_30.white },
        ['@constant.language.symbol.ruby'] = { fg = colors.base_30.white },
        ['@selector.sass'] = { fg = colors.base_30.purple },
        ['@support.type.primitive.ts'] = { fg = colors.base_30.teal },
        ['@storage.type.cs'] = { fg = colors.base_30.teal },
        ['@entity.name.variable.local.cs'] = { fg = colors.base_30.purple },
        ['@punctuation.definition.template-expression.begin'] = { fg = colors.base_30.blue },
        ['@meta.template.expression'] = { fg = colors.base_30.white },
        ['@keyword.operator.module'] = { fg = colors.base_30.blue },
        ['@support.type.type.flowtype'] = { fg = colors.base_30.pink },
        ['@support.type.primitive'] = { fg = colors.base_30.teal },
        ['@meta.property.object'] = { fg = colors.base_30.purple },
        ['@variable.parameter.function.js'] = { fg = colors.base_30.purple },
        ['@keyword.other.template.begin'] = { fg = colors.base_30.yellow },
        ['@keyword.other.substitution.begin'] = { fg = colors.base_30.yellow },
        ['@keyword.operator.assignment'] = { fg = colors.base_30.white },
        ['@keyword.operator.assignment.go'] = { fg = colors.base_30.teal },
        ['@keyword.operator.arithmetic.go'] = { fg = colors.base_30.blue },
        ['@entity.name.package.go'] = { fg = colors.base_30.teal },
        ['@support.type.prelude.elm'] = { fg = colors.base_30.white },
        ['@support.constant.elm'] = { fg = colors.base_30.white },
        ['@punctuation.quasi.element'] = { fg = colors.base_30.blue },
        ['@constant.character.entity'] = { fg = colors.base_30.purple },
        ['@entity.other.attribute-name.pseudo-element'] = { fg = colors.base_30.white },
        ['@entity.global.clojure'] = { fg = colors.base_30.teal },
        ['@meta.symbol.clojure'] = { fg = colors.base_30.purple },
        ['@constant.keyword.clojure'] = { fg = colors.base_30.white },
        ['@variable.parameter.function.coffee'] = { fg = colors.base_30.purple },
        ['@source.ini'] = { fg = colors.base_30.yellow },
        ['@meta.scope.prerequisites.makefile'] = { fg = colors.base_30.purple },
        ['@source.makefile'] = { fg = colors.base_30.teal },
        ['@storage.modifier.import.groovy'] = { fg = colors.base_30.teal },
        ['@meta.method.groovy'] = { fg = colors.base_30.pink },
        ['@meta.definition.variable.name.groovy'] = { fg = colors.base_30.purple },
        ['@support.variable.semantic.hlsl'] = { fg = colors.base_30.teal },
        ['@support.type.texture.hlsl'] = { fg = colors.base_30.blue },
        ['@text.variable'] = { fg = colors.base_30.purple },
        ['@support.type.swift'] = { fg = colors.base_30.teal },
        ['@entity.name.function.xi'] = { fg = colors.base_30.teal },
        ['@entity.name.class.xi'] = { fg = colors.base_30.white },
        ['@constant.character.character-class.regexp.xi'] = { fg = colors.base_30.purple },
        ['@constant.regexp.xi'] = { fg = colors.base_30.blue },
        ['@keyword.control.xi'] = { fg = colors.base_30.white },
        ['@invalid.xi'] = { fg = colors.base_30.white },
        ['@beginning.punctuation.definition.quote.markdown.xi'] = { fg = colors.base_30.yellow },
        ['@beginning.punctuation.definition.list.markdown.xi'] = { fg = colors.base_16.base0F },
        ['@constant.character.xi'] = { fg = colors.base_30.pink },
        ['@accent.xi'] = { fg = colors.base_30.pink },
        ['@wikiword.xi'] = { fg = colors.base_30.white },
        ['@constant.other.color.rgb-value.xi'] = { fg = '#ffffff' },
        ['@punctuation.definition.tag.xi'] = { fg = colors.base_16.base0F },
        ['@entity.name.label.cs'] = { fg = colors.base_30.teal },
        ['@markup.heading.setext.markdown'] = { fg = colors.base_30.purple },
        ['@meta.brace.square'] = { fg = colors.base_30.white },
        ['@comment'] = { fg = colors.base_16.base0F, italic = true },
        ['@punctuation.definition.comment'] = { fg = colors.base_16.base0F, italic = true },
        ['@markup.quote.markdown'] = { fg = colors.base_16.base0F },
        ['@punctuation.definition.block.sequence.item.yaml'] = { fg = colors.base_30.white },
        ['@constant.language.symbol.elixir'] = { fg = colors.base_30.white },
        ['@entity.other.attribute-name.js'] = { fg = colors.base_30.white, italic = true },
        ['@comment.line.double-slash'] = { fg = colors.base_16.base0F, italic = true },
        ['@keyword.control.import.python'] = { fg = colors.base_30.blue, italic = true },
        ['@markup.italic.markdown'] = { fg = colors.base_30.blue, italic = true },
    }
}

-- Initialize base highlights
function Module.setup()
    -- Set all the polish highlights
    for group, opts in pairs(Module.polish_hl) do
        vim.api.nvim_set_hl(0, group, opts)
    end
end

-- Export the module
return Module
